services:
  postgres:
    image: postgres:15.8
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    
