services:
  postgres:
    image: postgres:17.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/home/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_CONFIG_ENABLE_PSQL=True
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
    
